name = "Modded CFO"
author = "MmeCromatique"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a346a9a9e91cf4bf4d248fd6ff1df1d0a9232f7fdc433019ec672263483e174"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
