name = "Modded CFO"
author = "MmeCromatique"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e429da5f750f858a3ce934c560dab776e54cf1532157cd665085344efa4baf17"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
