name = "Modded CFO"
author = "MmeCromatique"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e0edf91a28fa5d901fed54c6adf564958c16130e865e217fb3a09d3887c4598"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
